name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag kueue:latest
    - name: Check style - "kueue"
      run: docker run --rm -it kueue:latest flakehell lint kueue
    - name: Check style - "tests"
      run: docker run --rm -it kueue:latest flakehell lint tests
